### PR TITLE
feat: enable buildFeatures.buildConfig for android gradle plugin 8+

### PR DESCRIPTION
**Pull request by radko93**
Add support for RN 0.73.
Similar to https://github.com/th3rdwave/react-native-safe-area-context/pull/455

### CODE REVIEW

**Review by tschoffelen — COMMENTED** [review]
Thanks for this! Will this work for older versions of grade as well? (I guess just Gradle 7?)

**Comment by radko93** [comment]
@tschoffelen as per https://github.com/th3rdwave/react-native-safe-area-context/pull/455#issuecomment-1805636431 it will work in AGP7+

**Review by tschoffelen — APPROVED** [review]
Ah amazing, thanks so much!

**Comment by tschoffelen** [comment]
Released to NPM as `react-native-email-link@1.14.8`. Thanks again for your contribution!

**Pull request merged**
